[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base = "light"
primaryColor = "#6c63ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#000000"
font = "sans serif"
